/**
 * Emit the VALUES clause for brsr_assignment_blocks seed in
 * supabase/migrations/014_question_collaboration.sql from lib/brsr/blockIndex.
 *
 * Usage: npx tsx scripts/generate-block-map.ts
 * Paste the printed VALUES into the migration INSERT, then run
 * lib/brsr/blockMapSync.test.ts to confirm sync.
 */

import { allBlockIds, getBlock, representativeCodeFor } from "../lib/brsr/blockIndex";

function sqlQuote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const rows = allBlockIds().map((id) => {
  const block = getBlock(id);
  const code = representativeCodeFor(id);
  if (!block || !code) {
    throw new Error(`Missing meta for block ${id}`);
  }
  return { block_id: id, panel_id: block.panelId, question_code: code };
});

const values = rows
  .map(
    (r) =>
      `  (${sqlQuote(r.block_id)}, ${sqlQuote(r.panel_id)}, ${sqlQuote(r.question_code)})`
  )
  .join(",\n");

process.stdout.write(
  `-- Generated by scripts/generate-block-map.ts (${rows.length} rows)\n` +
    `INSERT INTO public.brsr_assignment_blocks (block_id, panel_id, question_code)\n` +
    `VALUES\n${values}\n` +
    `ON CONFLICT (block_id) DO UPDATE SET\n` +
    `  panel_id = EXCLUDED.panel_id,\n` +
    `  question_code = EXCLUDED.question_code;\n`
);
