import type { CalcRule } from "./types";

/** Calculation rules for all display-only cells across all panels */
export const CALC_RULES: CalcRule[] = [
  // General Data – PPP-adjusted revenue
  { type: "formula", outputId: "gdata_rev_ppp_cy_display", formula: "gdata_turnover_cy/gdata_ppp_cy", decimals: 2 },
  { type: "formula", outputId: "gdata_rev_ppp_py_display", formula: "gdata_turnover_py/gdata_ppp_py", decimals: 2 },
  // General Data – headcount sums
  { type: "sum", outputId: "gdata_emp_perm_sum", sumIds: ["gdata_emp_perm_m", "gdata_emp_perm_f", "gdata_emp_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_emp_oth_sum", sumIds: ["gdata_emp_oth_m", "gdata_emp_oth_f", "gdata_emp_oth_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_wrk_perm_sum", sumIds: ["gdata_wrk_perm_m", "gdata_wrk_perm_f", "gdata_wrk_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_wrk_oth_sum", sumIds: ["gdata_wrk_oth_m", "gdata_wrk_oth_f", "gdata_wrk_oth_o"], decimals: 0 },
  // Section A – location counts
  { type: "sum", outputId: "gen_18_nat_sum", sumIds: ["gen_18_nat_plants", "gen_18_nat_offices"], decimals: 0 },
  { type: "sum", outputId: "gen_18_int_sum", sumIds: ["gen_18_int_plants", "gen_18_int_offices"], decimals: 0 },
  // Section A – employee/worker percentage breakdowns
  { type: "pct", outputId: "gen_20a_emp_perm_m_pct", num: "gen_20a_emp_perm_m", denom: "gen_20a_emp_perm_total" },
  { type: "pct", outputId: "gen_20a_emp_perm_f_pct", num: "gen_20a_emp_perm_f", denom: "gen_20a_emp_perm_total" },
  { type: "pct", outputId: "gen_20a_emp_other_m_pct", num: "gen_20a_emp_other_m", denom: "gen_20a_emp_other_total" },
  { type: "pct", outputId: "gen_20a_emp_other_f_pct", num: "gen_20a_emp_other_f", denom: "gen_20a_emp_other_total" },
  { type: "pct", outputId: "gen_20a_wrk_perm_m_pct", num: "gen_20a_wrk_perm_m", denom: "gen_20a_wrk_perm_total" },
  { type: "pct", outputId: "gen_20a_wrk_perm_f_pct", num: "gen_20a_wrk_perm_f", denom: "gen_20a_wrk_perm_total" },
  { type: "pct", outputId: "gen_20a_wrk_other_m_pct", num: "gen_20a_wrk_other_m", denom: "gen_20a_wrk_other_total" },
  { type: "pct", outputId: "gen_20a_wrk_other_f_pct", num: "gen_20a_wrk_other_f", denom: "gen_20a_wrk_other_total" },
  { type: "pct", outputId: "gen_20b_emp_perm_m_pct", num: "gen_20b_emp_perm_m", denom: "gen_20b_emp_perm_total" },
  { type: "pct", outputId: "gen_20b_emp_perm_f_pct", num: "gen_20b_emp_perm_f", denom: "gen_20b_emp_perm_total" },
  { type: "pct", outputId: "gen_20b_emp_other_m_pct", num: "gen_20b_emp_other_m", denom: "gen_20b_emp_other_total" },
  { type: "pct", outputId: "gen_20b_emp_other_f_pct", num: "gen_20b_emp_other_f", denom: "gen_20b_emp_other_total" },
  { type: "pct", outputId: "gen_20b_wrk_perm_m_pct", num: "gen_20b_wrk_perm_m", denom: "gen_20b_wrk_perm_total" },
  { type: "pct", outputId: "gen_20b_wrk_perm_f_pct", num: "gen_20b_wrk_perm_f", denom: "gen_20b_wrk_perm_total" },
  { type: "pct", outputId: "gen_20b_wrk_other_m_pct", num: "gen_20b_wrk_other_m", denom: "gen_20b_wrk_other_total" },
  { type: "pct", outputId: "gen_20b_wrk_other_f_pct", num: "gen_20b_wrk_other_f", denom: "gen_20b_wrk_other_total" },
  { type: "pct", outputId: "gen_21_bod_pct", num: "gen_21_bod_f", denom: "gen_21_bod_total" },
  { type: "pct", outputId: "gen_21_kmp_pct", num: "gen_21_kmp_f", denom: "gen_21_kmp_total" },

  // P6 – Energy sums
  { type: "sum", outputId: "p6_e1_re_total_cy", sumIds: ["p6_e1_re_el_cy", "p6_e1_re_fuel_cy", "p6_e1_re_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_re_total_py", sumIds: ["p6_e1_re_el_py", "p6_e1_re_fuel_py", "p6_e1_re_oth_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_nre_total_cy", sumIds: ["p6_e1_nre_el_cy", "p6_e1_nre_fuel_cy", "p6_e1_nre_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_nre_total_py", sumIds: ["p6_e1_nre_el_py", "p6_e1_nre_fuel_py", "p6_e1_nre_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e1_intensity_cy", formula: "(p6_e1_re_el_cy+p6_e1_re_fuel_cy+p6_e1_re_oth_cy+p6_e1_nre_el_cy+p6_e1_nre_fuel_cy+p6_e1_nre_oth_cy)/p6_e1_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_py", formula: "(p6_e1_re_el_py+p6_e1_re_fuel_py+p6_e1_re_oth_py+p6_e1_nre_el_py+p6_e1_nre_fuel_py+p6_e1_nre_oth_py)/p6_e1_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_ppp_cy", formula: "(p6_e1_re_el_cy+p6_e1_re_fuel_cy+p6_e1_re_oth_cy+p6_e1_nre_el_cy+p6_e1_nre_fuel_cy+p6_e1_nre_oth_cy)/p6_e1_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_ppp_py", formula: "(p6_e1_re_el_py+p6_e1_re_fuel_py+p6_e1_re_oth_py+p6_e1_nre_el_py+p6_e1_nre_fuel_py+p6_e1_nre_oth_py)/p6_e1_rev_ppp_py", decimals: 6 },
  // P6 – Water sum + intensity
  { type: "sum", outputId: "p6_e3_with_total_cy", sumIds: ["p6_e3_surf_cy", "p6_e3_grnd_cy", "p6_e3_3p_cy", "p6_e3_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e3_with_total_py", sumIds: ["p6_e3_surf_py", "p6_e3_grnd_py", "p6_e3_3p_py", "p6_e3_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e3_intensity_cy", formula: "p6_e3_cons_cy/p6_e3_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_py", formula: "p6_e3_cons_py/p6_e3_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_ppp_cy", formula: "p6_e3_cons_cy/p6_e3_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_ppp_py", formula: "p6_e3_cons_py/p6_e3_rev_ppp_py", decimals: 6 },
  // P6 – GHG sum + intensity
  { type: "sum", outputId: "p6_e7_s1s2_cy", sumIds: ["p6_e7_s1_cy", "p6_e7_s2_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e7_s1s2_py", sumIds: ["p6_e7_s1_py", "p6_e7_s2_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e7_intensity_cy", formula: "(p6_e7_s1_cy+p6_e7_s2_cy)/p6_e7_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_py", formula: "(p6_e7_s1_py+p6_e7_s2_py)/p6_e7_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_ppp_cy", formula: "(p6_e7_s1_cy+p6_e7_s2_cy)/p6_e7_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_ppp_py", formula: "(p6_e7_s1_py+p6_e7_s2_py)/p6_e7_rev_ppp_py", decimals: 6 },
  // P6 – Waste total, recovery, disposal
  { type: "sum", outputId: "p6_e9_total_cy", sumIds: ["p6_e9_plast_cy", "p6_e9_ew_cy", "p6_e9_bio_cy", "p6_e9_cd_cy", "p6_e9_batt_cy", "p6_e9_radio_cy", "p6_e9_ohaz_cy", "p6_e9_onh_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_total_py", sumIds: ["p6_e9_plast_py", "p6_e9_ew_py", "p6_e9_bio_py", "p6_e9_cd_py", "p6_e9_batt_py", "p6_e9_radio_py", "p6_e9_ohaz_py", "p6_e9_onh_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_rec_total_cy", sumIds: ["p6_e9_rec_recy_cy", "p6_e9_rec_reuse_cy", "p6_e9_rec_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_rec_total_py", sumIds: ["p6_e9_rec_recy_py", "p6_e9_rec_reuse_py", "p6_e9_rec_oth_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_disp_total_cy", sumIds: ["p6_e9_disp_inc_cy", "p6_e9_disp_land_cy", "p6_e9_disp_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_disp_total_py", sumIds: ["p6_e9_disp_inc_py", "p6_e9_disp_land_py", "p6_e9_disp_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e9_intensity_cy", formula: "(p6_e9_plast_cy+p6_e9_ew_cy+p6_e9_bio_cy+p6_e9_cd_cy+p6_e9_batt_cy+p6_e9_radio_cy+p6_e9_ohaz_cy+p6_e9_onh_cy)/p6_e9_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_py", formula: "(p6_e9_plast_py+p6_e9_ew_py+p6_e9_bio_py+p6_e9_cd_py+p6_e9_batt_py+p6_e9_radio_py+p6_e9_ohaz_py+p6_e9_onh_py)/p6_e9_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_ppp_cy", formula: "(p6_e9_plast_cy+p6_e9_ew_cy+p6_e9_bio_cy+p6_e9_cd_cy+p6_e9_batt_cy+p6_e9_radio_cy+p6_e9_ohaz_cy+p6_e9_onh_cy)/p6_e9_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_ppp_py", formula: "(p6_e9_plast_py+p6_e9_ew_py+p6_e9_bio_py+p6_e9_cd_py+p6_e9_batt_py+p6_e9_radio_py+p6_e9_ohaz_py+p6_e9_onh_py)/p6_e9_rev_ppp_py", decimals: 6 },

  // P1 – training coverage and payable days
  { type: "pct", outputId: "calc_p1_pct_1", num: "p1_e1_bod_covered", denom: "p1_e1_bod_total" },
  { type: "pct", outputId: "calc_p1_pct_2", num: "p1_e1_kmp_covered", denom: "p1_e1_kmp_total" },
  { type: "pct", outputId: "calc_p1_pct_3", num: "p1_e1_emp_covered", denom: "p1_e1_emp_total" },
  { type: "pct", outputId: "calc_p1_pct_4", num: "p1_e1_wrk_covered", denom: "p1_e1_wrk_total" },
  { type: "pct", outputId: "calc_p1_pct_5", num: "p1_l1_covered_val", denom: "p1_l1_total_val" },
  { type: "formula", outputId: "calc_p1_formula_1", formula: "p1_e8_ap_cy*365/p1_e8_cost_cy", decimals: 2 },
  { type: "formula", outputId: "calc_p1_formula_2", formula: "p1_e8_ap_py*365/p1_e8_cost_py", decimals: 2 },
  // P2 – R&D and capex percentages
  { type: "pct", outputId: "calc_p2_pct_1", num: "p2_e1_rd_env_cy", denom: "p2_e1_rd_cy" },
  { type: "pct", outputId: "calc_p2_pct_2", num: "p2_e1_rd_env_py", denom: "p2_e1_rd_py" },
  { type: "pct", outputId: "calc_p2_pct_3", num: "p2_e1_capex_env_cy", denom: "p2_e1_capex_cy" },
  { type: "pct", outputId: "calc_p2_pct_4", num: "p2_e1_capex_env_py", denom: "p2_e1_capex_py" },
  { type: "pct", outputId: "calc_p2_pct_5", num: "p2_e2_sustainable", denom: "p2_e2_total" },
  { type: "pct", outputId: "calc_p2_pct_6", num: "p2_l3_row0_recycled", denom: "p2_l3_row0_total" },
  // P3 – benefits coverage percentages
  { type: "pct", outputId: "calc_p3_pct_1", num: "p3_e1a_perm_m_hi", denom: "p3_e1a_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_2", num: "p3_e1a_perm_m_ac", denom: "p3_e1a_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_3", num: "p3_e1a_perm_m_mat", denom: "p3_e1a_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_4", num: "p3_e1a_perm_m_pat", denom: "p3_e1a_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_5", num: "p3_e1a_perm_m_dc", denom: "p3_e1a_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_6", num: "p3_e1a_perm_f_hi", denom: "p3_e1a_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_7", num: "p3_e1a_perm_f_ac", denom: "p3_e1a_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_8", num: "p3_e1a_perm_f_mat", denom: "p3_e1a_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_9", num: "p3_e1a_perm_f_pat", denom: "p3_e1a_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_10", num: "p3_e1a_perm_f_dc", denom: "p3_e1a_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_11", num: "p3_e1a_oth_m_hi", denom: "p3_e1a_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_12", num: "p3_e1a_oth_m_ac", denom: "p3_e1a_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_13", num: "p3_e1a_oth_m_mat", denom: "p3_e1a_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_14", num: "p3_e1a_oth_m_pat", denom: "p3_e1a_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_15", num: "p3_e1a_oth_m_dc", denom: "p3_e1a_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_16", num: "p3_e1a_oth_f_hi", denom: "p3_e1a_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_17", num: "p3_e1a_oth_f_ac", denom: "p3_e1a_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_18", num: "p3_e1a_oth_f_mat", denom: "p3_e1a_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_19", num: "p3_e1a_oth_f_pat", denom: "p3_e1a_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_20", num: "p3_e1a_oth_f_dc", denom: "p3_e1a_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_21", num: "p3_e1b_perm_m_hi", denom: "p3_e1b_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_22", num: "p3_e1b_perm_m_ac", denom: "p3_e1b_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_23", num: "p3_e1b_perm_m_mat", denom: "p3_e1b_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_24", num: "p3_e1b_perm_m_pat", denom: "p3_e1b_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_25", num: "p3_e1b_perm_m_dc", denom: "p3_e1b_perm_m_t" },
  { type: "pct", outputId: "calc_p3_pct_26", num: "p3_e1b_perm_f_hi", denom: "p3_e1b_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_27", num: "p3_e1b_perm_f_ac", denom: "p3_e1b_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_28", num: "p3_e1b_perm_f_mat", denom: "p3_e1b_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_29", num: "p3_e1b_perm_f_pat", denom: "p3_e1b_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_30", num: "p3_e1b_perm_f_dc", denom: "p3_e1b_perm_f_t" },
  { type: "pct", outputId: "calc_p3_pct_31", num: "p3_e1b_oth_m_hi", denom: "p3_e1b_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_32", num: "p3_e1b_oth_m_ac", denom: "p3_e1b_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_33", num: "p3_e1b_oth_m_mat", denom: "p3_e1b_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_34", num: "p3_e1b_oth_m_pat", denom: "p3_e1b_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_35", num: "p3_e1b_oth_m_dc", denom: "p3_e1b_oth_m_t" },
  { type: "pct", outputId: "calc_p3_pct_36", num: "p3_e1b_oth_f_hi", denom: "p3_e1b_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_37", num: "p3_e1b_oth_f_ac", denom: "p3_e1b_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_38", num: "p3_e1b_oth_f_mat", denom: "p3_e1b_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_39", num: "p3_e1b_oth_f_pat", denom: "p3_e1b_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_40", num: "p3_e1b_oth_f_dc", denom: "p3_e1b_oth_f_t" },
  { type: "pct", outputId: "calc_p3_pct_41", num: "p3_e1c_cy_spend", denom: "p3_e1c_cy_rev" },
  { type: "pct", outputId: "calc_p3_pct_42", num: "p3_e1c_py_spend", denom: "p3_e1c_py_rev" },
  { type: "pct", outputId: "calc_p3_pct_43", num: "p3_e7_emp_m_u_cy", denom: "p3_e7_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_44", num: "p3_e7_emp_m_u_py", denom: "p3_e7_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_45", num: "p3_e7_emp_f_u_cy", denom: "p3_e7_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_46", num: "p3_e7_emp_f_u_py", denom: "p3_e7_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_47", num: "p3_e7_wrk_m_u_cy", denom: "p3_e7_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_48", num: "p3_e7_wrk_f_u_cy", denom: "p3_e7_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_49", num: "p3_e8_emp_m_hs_cy", denom: "p3_e8_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_50", num: "p3_e8_emp_m_sk_cy", denom: "p3_e8_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_51", num: "p3_e8_emp_m_hs_py", denom: "p3_e8_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_52", num: "p3_e8_emp_m_sk_py", denom: "p3_e8_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_53", num: "p3_e8_emp_f_hs_cy", denom: "p3_e8_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_54", num: "p3_e8_emp_f_sk_cy", denom: "p3_e8_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_55", num: "p3_e8_emp_f_hs_py", denom: "p3_e8_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_56", num: "p3_e8_emp_f_sk_py", denom: "p3_e8_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_57", num: "p3_e8_wrk_m_hs_cy", denom: "p3_e8_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_58", num: "p3_e8_wrk_m_sk_cy", denom: "p3_e8_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_59", num: "p3_e8_wrk_m_hs_py", denom: "p3_e8_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_60", num: "p3_e8_wrk_m_sk_py", denom: "p3_e8_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_61", num: "p3_e8_wrk_f_hs_cy", denom: "p3_e8_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_62", num: "p3_e8_wrk_f_sk_cy", denom: "p3_e8_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_63", num: "p3_e8_wrk_f_hs_py", denom: "p3_e8_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_64", num: "p3_e8_wrk_f_sk_py", denom: "p3_e8_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_65", num: "p3_e9_emp_m_r_cy", denom: "p3_e9_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_66", num: "p3_e9_emp_m_r_py", denom: "p3_e9_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_67", num: "p3_e9_emp_f_r_cy", denom: "p3_e9_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_68", num: "p3_e9_emp_f_r_py", denom: "p3_e9_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_pct_69", num: "p3_e9_wrk_m_r_cy", denom: "p3_e9_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_70", num: "p3_e9_wrk_m_r_py", denom: "p3_e9_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_pct_71", num: "p3_e9_wrk_f_r_cy", denom: "p3_e9_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_pct_72", num: "p3_e9_wrk_f_r_py", denom: "p3_e9_wrk_f_t_py" },
  // P5 – human rights training + pay equity + complaints
  { type: "pct", outputId: "calc_p5_pct_1", num: "p5_e1_emp_perm_c_cy", denom: "p5_e1_emp_perm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_2", num: "p5_e1_emp_perm_c_py", denom: "p5_e1_emp_perm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_3", num: "p5_e1_emp_oth_c_cy", denom: "p5_e1_emp_oth_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_4", num: "p5_e1_emp_oth_c_py", denom: "p5_e1_emp_oth_t_py" },
  { type: "pct", outputId: "calc_p5_pct_5", num: "p5_e1_wrk_perm_c_cy", denom: "p5_e1_wrk_perm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_6", num: "p5_e1_wrk_perm_c_py", denom: "p5_e1_wrk_perm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_7", num: "p5_e1_wrk_oth_c_cy", denom: "p5_e1_wrk_oth_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_8", num: "p5_e1_wrk_oth_c_py", denom: "p5_e1_wrk_oth_t_py" },
  { type: "pct", outputId: "calc_p5_pct_9", num: "p5_e2_emp_pm_eq_cy", denom: "p5_e2_emp_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_10", num: "p5_e2_emp_pm_more_cy", denom: "p5_e2_emp_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_11", num: "p5_e2_emp_pm_eq_py", denom: "p5_e2_emp_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_12", num: "p5_e2_emp_pm_more_py", denom: "p5_e2_emp_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_13", num: "p5_e2_emp_pf_eq_cy", denom: "p5_e2_emp_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_14", num: "p5_e2_emp_pf_more_cy", denom: "p5_e2_emp_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_15", num: "p5_e2_emp_pf_eq_py", denom: "p5_e2_emp_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_16", num: "p5_e2_emp_pf_more_py", denom: "p5_e2_emp_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_17", num: "p5_e2_wrk_pm_eq_cy", denom: "p5_e2_wrk_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_18", num: "p5_e2_wrk_pm_more_cy", denom: "p5_e2_wrk_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_19", num: "p5_e2_wrk_pm_eq_py", denom: "p5_e2_wrk_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_20", num: "p5_e2_wrk_pm_more_py", denom: "p5_e2_wrk_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_21", num: "p5_e2_wrk_pf_eq_cy", denom: "p5_e2_wrk_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_22", num: "p5_e2_wrk_pf_more_cy", denom: "p5_e2_wrk_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_23", num: "p5_e2_wrk_pf_eq_py", denom: "p5_e2_wrk_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_24", num: "p5_e2_wrk_pf_more_py", denom: "p5_e2_wrk_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_25", num: "p5_e3b_cy_f", denom: "p5_e3b_cy_t" },
  { type: "pct", outputId: "calc_p5_pct_26", num: "p5_e3b_py_f", denom: "p5_e3b_py_t" },
  { type: "pct", outputId: "calc_p5_pct_27", num: "p5_e7_tot_cy", denom: "p5_e7_f_cy" },
  { type: "pct", outputId: "calc_p5_pct_28", num: "p5_e7_tot_py", denom: "p5_e7_f_py" },
  // P8 – geographic beneficiary percentages
  { type: "pct", outputId: "calc_p8_pct_1", num: "p8_e5_rural_w_cy", denom: "p8_e5_rural_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_2", num: "p8_e5_rural_w_py", denom: "p8_e5_rural_t_py" },
  { type: "pct", outputId: "calc_p8_pct_3", num: "p8_e5_semi_w_cy", denom: "p8_e5_semi_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_4", num: "p8_e5_semi_w_py", denom: "p8_e5_semi_t_py" },
  { type: "pct", outputId: "calc_p8_pct_5", num: "p8_e5_urb_w_cy", denom: "p8_e5_urb_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_6", num: "p8_e5_urb_w_py", denom: "p8_e5_urb_t_py" },
  { type: "pct", outputId: "calc_p8_pct_7", num: "p8_e5_metro_w_cy", denom: "p8_e5_metro_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_8", num: "p8_e5_metro_w_py", denom: "p8_e5_metro_t_py" },
  { type: "pct", outputId: "calc_p8_pct_9", num: "p8_l3_pref", denom: "p8_l3_total" },
  { type: "pct", outputId: "calc_p8_pct_10", num: "p8_l6_1_vuln", denom: "p8_l6_1_tot" },
  // P9 – consumer complaint resolution
  { type: "pct", outputId: "calc_p9_pct_1", num: "p9_e7b_cy", denom: "p9_e7a_cy" },
  { type: "pct", outputId: "calc_p9_pct_2", num: "p9_e7b_py", denom: "p9_e7a_py" },
];
