import type { CalcRule } from "./types";

/** Calculation rules for all display-only cells across all panels */
export const CALC_RULES: CalcRule[] = [
  // General Data – PPP-adjusted revenue
  { type: "formula", outputId: "gdata_rev_ppp_cy_display", formula: "gdata_turnover_cy/gdata_ppp_cy", decimals: 2 },
  { type: "formula", outputId: "gdata_rev_ppp_py_display", formula: "gdata_turnover_py/gdata_ppp_py", decimals: 2 },
  // General Data – headcount sums
  { type: "sum", outputId: "gdata_emp_perm_sum", sumIds: ["gdata_emp_perm_m", "gdata_emp_perm_f", "gdata_emp_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_emp_oth_sum", sumIds: ["gdata_emp_oth_m", "gdata_emp_oth_f", "gdata_emp_oth_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_wrk_perm_sum", sumIds: ["gdata_wrk_perm_m", "gdata_wrk_perm_f", "gdata_wrk_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gdata_wrk_oth_sum", sumIds: ["gdata_wrk_oth_m", "gdata_wrk_oth_f", "gdata_wrk_oth_o"], decimals: 0 },
  // Section A – location counts
  { type: "sum", outputId: "gen_18_nat_sum", sumIds: ["gen_18_nat_plants", "gen_18_nat_offices"], decimals: 0 },
  { type: "sum", outputId: "gen_18_int_sum", sumIds: ["gen_18_int_plants", "gen_18_int_offices"], decimals: 0 },
  // Section A – employee/worker totals (Total A = B + C + D) and percentage breakdowns
  { type: "sum", outputId: "gen_20a_emp_perm_total", sumIds: ["gen_20a_emp_perm_m", "gen_20a_emp_perm_f", "gen_20a_emp_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_emp_other_total", sumIds: ["gen_20a_emp_other_m", "gen_20a_emp_other_f", "gen_20a_emp_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_perm_total", sumIds: ["gen_20a_wrk_perm_m", "gen_20a_wrk_perm_f", "gen_20a_wrk_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_other_total", sumIds: ["gen_20a_wrk_other_m", "gen_20a_wrk_other_f", "gen_20a_wrk_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_perm_total", sumIds: ["gen_20b_emp_perm_m", "gen_20b_emp_perm_f", "gen_20b_emp_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_other_total", sumIds: ["gen_20b_emp_other_m", "gen_20b_emp_other_f", "gen_20b_emp_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_perm_total", sumIds: ["gen_20b_wrk_perm_m", "gen_20b_wrk_perm_f", "gen_20b_wrk_perm_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_other_total", sumIds: ["gen_20b_wrk_other_m", "gen_20b_wrk_other_f", "gen_20b_wrk_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_emp_total", sumIds: ["gen_20a_emp_perm_total", "gen_20a_emp_other_total"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_emp_total_m", sumIds: ["gen_20a_emp_perm_m", "gen_20a_emp_other_m"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_emp_total_f", sumIds: ["gen_20a_emp_perm_f", "gen_20a_emp_other_f"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_emp_total_o", sumIds: ["gen_20a_emp_perm_o", "gen_20a_emp_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_total", sumIds: ["gen_20a_wrk_perm_total", "gen_20a_wrk_other_total"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_total_m", sumIds: ["gen_20a_wrk_perm_m", "gen_20a_wrk_other_m"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_total_f", sumIds: ["gen_20a_wrk_perm_f", "gen_20a_wrk_other_f"], decimals: 0 },
  { type: "sum", outputId: "gen_20a_wrk_total_o", sumIds: ["gen_20a_wrk_perm_o", "gen_20a_wrk_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_total", sumIds: ["gen_20b_emp_perm_total", "gen_20b_emp_other_total"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_total_m", sumIds: ["gen_20b_emp_perm_m", "gen_20b_emp_other_m"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_total_f", sumIds: ["gen_20b_emp_perm_f", "gen_20b_emp_other_f"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_emp_total_o", sumIds: ["gen_20b_emp_perm_o", "gen_20b_emp_other_o"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_total", sumIds: ["gen_20b_wrk_perm_total", "gen_20b_wrk_other_total"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_total_m", sumIds: ["gen_20b_wrk_perm_m", "gen_20b_wrk_other_m"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_total_f", sumIds: ["gen_20b_wrk_perm_f", "gen_20b_wrk_other_f"], decimals: 0 },
  { type: "sum", outputId: "gen_20b_wrk_total_o", sumIds: ["gen_20b_wrk_perm_o", "gen_20b_wrk_other_o"], decimals: 0 },
  { type: "pct", outputId: "gen_20a_emp_perm_m_pct", num: "gen_20a_emp_perm_m", denom: "gen_20a_emp_perm_total" },
  { type: "pct", outputId: "gen_20a_emp_perm_f_pct", num: "gen_20a_emp_perm_f", denom: "gen_20a_emp_perm_total" },
  { type: "pct", outputId: "gen_20a_emp_perm_o_pct", num: "gen_20a_emp_perm_o", denom: "gen_20a_emp_perm_total" },
  { type: "pct", outputId: "gen_20a_emp_other_m_pct", num: "gen_20a_emp_other_m", denom: "gen_20a_emp_other_total" },
  { type: "pct", outputId: "gen_20a_emp_other_f_pct", num: "gen_20a_emp_other_f", denom: "gen_20a_emp_other_total" },
  { type: "pct", outputId: "gen_20a_emp_other_o_pct", num: "gen_20a_emp_other_o", denom: "gen_20a_emp_other_total" },
  { type: "pct", outputId: "gen_20a_wrk_perm_m_pct", num: "gen_20a_wrk_perm_m", denom: "gen_20a_wrk_perm_total" },
  { type: "pct", outputId: "gen_20a_wrk_perm_f_pct", num: "gen_20a_wrk_perm_f", denom: "gen_20a_wrk_perm_total" },
  { type: "pct", outputId: "gen_20a_wrk_perm_o_pct", num: "gen_20a_wrk_perm_o", denom: "gen_20a_wrk_perm_total" },
  { type: "pct", outputId: "gen_20a_wrk_other_m_pct", num: "gen_20a_wrk_other_m", denom: "gen_20a_wrk_other_total" },
  { type: "pct", outputId: "gen_20a_wrk_other_f_pct", num: "gen_20a_wrk_other_f", denom: "gen_20a_wrk_other_total" },
  { type: "pct", outputId: "gen_20a_wrk_other_o_pct", num: "gen_20a_wrk_other_o", denom: "gen_20a_wrk_other_total" },
  { type: "pct", outputId: "gen_20a_emp_total_m_pct", num: "gen_20a_emp_total_m", denom: "gen_20a_emp_total" },
  { type: "pct", outputId: "gen_20a_emp_total_f_pct", num: "gen_20a_emp_total_f", denom: "gen_20a_emp_total" },
  { type: "pct", outputId: "gen_20a_emp_total_o_pct", num: "gen_20a_emp_total_o", denom: "gen_20a_emp_total" },
  { type: "pct", outputId: "gen_20a_wrk_total_m_pct", num: "gen_20a_wrk_total_m", denom: "gen_20a_wrk_total" },
  { type: "pct", outputId: "gen_20a_wrk_total_f_pct", num: "gen_20a_wrk_total_f", denom: "gen_20a_wrk_total" },
  { type: "pct", outputId: "gen_20a_wrk_total_o_pct", num: "gen_20a_wrk_total_o", denom: "gen_20a_wrk_total" },
  { type: "pct", outputId: "gen_20b_emp_perm_m_pct", num: "gen_20b_emp_perm_m", denom: "gen_20b_emp_perm_total" },
  { type: "pct", outputId: "gen_20b_emp_perm_f_pct", num: "gen_20b_emp_perm_f", denom: "gen_20b_emp_perm_total" },
  { type: "pct", outputId: "gen_20b_emp_perm_o_pct", num: "gen_20b_emp_perm_o", denom: "gen_20b_emp_perm_total" },
  { type: "pct", outputId: "gen_20b_emp_other_m_pct", num: "gen_20b_emp_other_m", denom: "gen_20b_emp_other_total" },
  { type: "pct", outputId: "gen_20b_emp_other_f_pct", num: "gen_20b_emp_other_f", denom: "gen_20b_emp_other_total" },
  { type: "pct", outputId: "gen_20b_emp_other_o_pct", num: "gen_20b_emp_other_o", denom: "gen_20b_emp_other_total" },
  { type: "pct", outputId: "gen_20b_wrk_perm_m_pct", num: "gen_20b_wrk_perm_m", denom: "gen_20b_wrk_perm_total" },
  { type: "pct", outputId: "gen_20b_wrk_perm_f_pct", num: "gen_20b_wrk_perm_f", denom: "gen_20b_wrk_perm_total" },
  { type: "pct", outputId: "gen_20b_wrk_perm_o_pct", num: "gen_20b_wrk_perm_o", denom: "gen_20b_wrk_perm_total" },
  { type: "pct", outputId: "gen_20b_wrk_other_m_pct", num: "gen_20b_wrk_other_m", denom: "gen_20b_wrk_other_total" },
  { type: "pct", outputId: "gen_20b_wrk_other_f_pct", num: "gen_20b_wrk_other_f", denom: "gen_20b_wrk_other_total" },
  { type: "pct", outputId: "gen_20b_wrk_other_o_pct", num: "gen_20b_wrk_other_o", denom: "gen_20b_wrk_other_total" },
  { type: "pct", outputId: "gen_20b_emp_total_m_pct", num: "gen_20b_emp_total_m", denom: "gen_20b_emp_total" },
  { type: "pct", outputId: "gen_20b_emp_total_f_pct", num: "gen_20b_emp_total_f", denom: "gen_20b_emp_total" },
  { type: "pct", outputId: "gen_20b_emp_total_o_pct", num: "gen_20b_emp_total_o", denom: "gen_20b_emp_total" },
  { type: "pct", outputId: "gen_20b_wrk_total_m_pct", num: "gen_20b_wrk_total_m", denom: "gen_20b_wrk_total" },
  { type: "pct", outputId: "gen_20b_wrk_total_f_pct", num: "gen_20b_wrk_total_f", denom: "gen_20b_wrk_total" },
  { type: "pct", outputId: "gen_20b_wrk_total_o_pct", num: "gen_20b_wrk_total_o", denom: "gen_20b_wrk_total" },
  { type: "pct", outputId: "gen_21_bod_pct", num: "gen_21_bod_f", denom: "gen_21_bod_total" },
  { type: "pct", outputId: "gen_21_kmp_pct", num: "gen_21_kmp_f", denom: "gen_21_kmp_total" },

  // P6 – Energy sums
  { type: "sum", outputId: "p6_e1_re_total_cy", sumIds: ["p6_e1_re_el_cy", "p6_e1_re_fuel_cy", "p6_e1_re_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_re_total_py", sumIds: ["p6_e1_re_el_py", "p6_e1_re_fuel_py", "p6_e1_re_oth_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_nre_total_cy", sumIds: ["p6_e1_nre_el_cy", "p6_e1_nre_fuel_cy", "p6_e1_nre_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_nre_total_py", sumIds: ["p6_e1_nre_el_py", "p6_e1_nre_fuel_py", "p6_e1_nre_oth_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_total_cy", sumIds: ["p6_e1_re_el_cy", "p6_e1_re_fuel_cy", "p6_e1_re_oth_cy", "p6_e1_nre_el_cy", "p6_e1_nre_fuel_cy", "p6_e1_nre_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e1_total_py", sumIds: ["p6_e1_re_el_py", "p6_e1_re_fuel_py", "p6_e1_re_oth_py", "p6_e1_nre_el_py", "p6_e1_nre_fuel_py", "p6_e1_nre_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e1_intensity_cy", formula: "(p6_e1_re_el_cy+p6_e1_re_fuel_cy+p6_e1_re_oth_cy+p6_e1_nre_el_cy+p6_e1_nre_fuel_cy+p6_e1_nre_oth_cy)/p6_e1_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_py", formula: "(p6_e1_re_el_py+p6_e1_re_fuel_py+p6_e1_re_oth_py+p6_e1_nre_el_py+p6_e1_nre_fuel_py+p6_e1_nre_oth_py)/p6_e1_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_ppp_cy", formula: "(p6_e1_re_el_cy+p6_e1_re_fuel_cy+p6_e1_re_oth_cy+p6_e1_nre_el_cy+p6_e1_nre_fuel_cy+p6_e1_nre_oth_cy)/p6_e1_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e1_intensity_ppp_py", formula: "(p6_e1_re_el_py+p6_e1_re_fuel_py+p6_e1_re_oth_py+p6_e1_nre_el_py+p6_e1_nre_fuel_py+p6_e1_nre_oth_py)/p6_e1_rev_ppp_py", decimals: 6 },
  // P6 – Water sum + intensity
  { type: "sum", outputId: "p6_e3_with_total_cy", sumIds: ["p6_e3_surf_cy", "p6_e3_grnd_cy", "p6_e3_3p_cy", "p6_e3_seawater_cy", "p6_e3_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e3_with_total_py", sumIds: ["p6_e3_surf_py", "p6_e3_grnd_py", "p6_e3_3p_py", "p6_e3_seawater_py", "p6_e3_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e3_intensity_cy", formula: "p6_e3_cons_cy/p6_e3_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_py", formula: "p6_e3_cons_py/p6_e3_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_ppp_cy", formula: "p6_e3_cons_cy/p6_e3_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e3_intensity_ppp_py", formula: "p6_e3_cons_py/p6_e3_rev_ppp_py", decimals: 6 },
  // P6 – Water discharge total
  { type: "sum", outputId: "p6_e4_tot_cy", sumIds: ["p6_e4_sw_nt_cy", "p6_e4_sw_t_cy", "p6_e4_grnd_nt_cy", "p6_e4_grnd_t_cy", "p6_e4_sea_nt_cy", "p6_e4_sea_t_cy", "p6_e4_3p_nt_cy", "p6_e4_3p_t_cy", "p6_e4_oth_nt_cy", "p6_e4_oth_t_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e4_tot_py", sumIds: ["p6_e4_sw_nt_py", "p6_e4_sw_t_py", "p6_e4_grnd_nt_py", "p6_e4_grnd_t_py", "p6_e4_sea_nt_py", "p6_e4_sea_t_py", "p6_e4_3p_nt_py", "p6_e4_3p_t_py", "p6_e4_oth_nt_py", "p6_e4_oth_t_py"], decimals: 2 },
  // P6 – GHG sum + intensity
  { type: "sum", outputId: "p6_e7_s1s2_cy", sumIds: ["p6_e7_s1_cy", "p6_e7_s2_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e7_s1s2_py", sumIds: ["p6_e7_s1_py", "p6_e7_s2_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e7_intensity_cy", formula: "(p6_e7_s1_cy+p6_e7_s2_cy)/p6_e7_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_py", formula: "(p6_e7_s1_py+p6_e7_s2_py)/p6_e7_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_ppp_cy", formula: "(p6_e7_s1_cy+p6_e7_s2_cy)/p6_e7_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e7_intensity_ppp_py", formula: "(p6_e7_s1_py+p6_e7_s2_py)/p6_e7_rev_ppp_py", decimals: 6 },
  // P6 – Waste total, recovery, disposal
  { type: "sum", outputId: "p6_e9_total_cy", sumIds: ["p6_e9_plast_cy", "p6_e9_ew_cy", "p6_e9_bio_cy", "p6_e9_cd_cy", "p6_e9_batt_cy", "p6_e9_radio_cy", "p6_e9_ohaz_cy", "p6_e9_onh_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_total_py", sumIds: ["p6_e9_plast_py", "p6_e9_ew_py", "p6_e9_bio_py", "p6_e9_cd_py", "p6_e9_batt_py", "p6_e9_radio_py", "p6_e9_ohaz_py", "p6_e9_onh_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_rec_total_cy", sumIds: ["p6_e9_rec_recy_cy", "p6_e9_rec_reuse_cy", "p6_e9_rec_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_rec_total_py", sumIds: ["p6_e9_rec_recy_py", "p6_e9_rec_reuse_py", "p6_e9_rec_oth_py"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_disp_total_cy", sumIds: ["p6_e9_disp_inc_cy", "p6_e9_disp_land_cy", "p6_e9_disp_oth_cy"], decimals: 2 },
  { type: "sum", outputId: "p6_e9_disp_total_py", sumIds: ["p6_e9_disp_inc_py", "p6_e9_disp_land_py", "p6_e9_disp_oth_py"], decimals: 2 },
  { type: "formula", outputId: "p6_e9_intensity_cy", formula: "(p6_e9_plast_cy+p6_e9_ew_cy+p6_e9_bio_cy+p6_e9_cd_cy+p6_e9_batt_cy+p6_e9_radio_cy+p6_e9_ohaz_cy+p6_e9_onh_cy)/p6_e9_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_py", formula: "(p6_e9_plast_py+p6_e9_ew_py+p6_e9_bio_py+p6_e9_cd_py+p6_e9_batt_py+p6_e9_radio_py+p6_e9_ohaz_py+p6_e9_onh_py)/p6_e9_rev_py", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_ppp_cy", formula: "(p6_e9_plast_cy+p6_e9_ew_cy+p6_e9_bio_cy+p6_e9_cd_cy+p6_e9_batt_cy+p6_e9_radio_cy+p6_e9_ohaz_cy+p6_e9_onh_cy)/p6_e9_rev_ppp_cy", decimals: 6 },
  { type: "formula", outputId: "p6_e9_intensity_ppp_py", formula: "(p6_e9_plast_py+p6_e9_ew_py+p6_e9_bio_py+p6_e9_cd_py+p6_e9_batt_py+p6_e9_radio_py+p6_e9_ohaz_py+p6_e9_onh_py)/p6_e9_rev_ppp_py", decimals: 6 },
  // P6 Leadership L1 – per-row water totals and intensity; L2 – Scope 3 intensity
  ...Array.from({ length: 10 }, (_, i) => {
    const r = `p6_l1_row${i}`;
    const sumW = [`${r}_surf_cy`, `${r}_grnd_cy`, `${r}_third_cy`, `${r}_sea_cy`, `${r}_oth_cy`];
    const sumWpy = [`${r}_surf_py`, `${r}_grnd_py`, `${r}_third_py`, `${r}_sea_py`, `${r}_oth_py`];
    const sumD = [`${r}_surf_a_nt_cy`, `${r}_surf_a_t_val_cy`, `${r}_grnd_b_nt_cy`, `${r}_grnd_b_t_val_cy`, `${r}_sea_c_nt_cy`, `${r}_sea_c_t_val_cy`, `${r}_third_d_nt_cy`, `${r}_third_d_t_val_cy`, `${r}_oth_e_nt_cy`, `${r}_oth_e_t_val_cy`];
    const sumDpy = [`${r}_surf_a_nt_py`, `${r}_surf_a_t_val_py`, `${r}_grnd_b_nt_py`, `${r}_grnd_b_t_val_py`, `${r}_sea_c_nt_py`, `${r}_sea_c_t_val_py`, `${r}_third_d_nt_py`, `${r}_third_d_t_val_py`, `${r}_oth_e_nt_py`, `${r}_oth_e_t_val_py`];
    return [
      { type: "sum" as const, outputId: `${r}_total_with_cy`, sumIds: sumW, decimals: 2 },
      { type: "sum" as const, outputId: `${r}_total_with_py`, sumIds: sumWpy, decimals: 2 },
      { type: "sum" as const, outputId: `${r}_total_disp_cy`, sumIds: sumD, decimals: 2 },
      { type: "sum" as const, outputId: `${r}_total_disp_py`, sumIds: sumDpy, decimals: 2 },
      { type: "formula" as const, outputId: `${r}_intensity_cy`, formula: `${r}_cons_cy/p6_e9_rev_cy`, decimals: 6 },
      { type: "formula" as const, outputId: `${r}_intensity_py`, formula: `${r}_cons_py/p6_e9_rev_py`, decimals: 6 },
    ];
  }).flat(),
  { type: "formula", outputId: "p6_l2_intensity_cy", formula: "p6_l2_s3_cy/p6_e9_rev_cy", decimals: 6 },
  { type: "formula", outputId: "p6_l2_intensity_py", formula: "p6_l2_s3_py/p6_e9_rev_py", decimals: 6 },

  // P1 – payable days
  { type: "formula", outputId: "calc_p1_formula_1", formula: "p1_e8_ap_cy/p1_e8_cost_cy", decimals: 2 },
  { type: "formula", outputId: "calc_p1_formula_2", formula: "p1_e8_ap_py/p1_e8_cost_py", decimals: 2 },
  // P1 Q9 – concentration of purchases/sales, RPTs (all percentage rows calculated)
  { type: "pct", outputId: "calc_p1_e9_purch_pct_cy", num: "p1_e9_purch_i_cy", denom: "p1_e9_purch_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_purch_pct_py", num: "p1_e9_purch_i_py", denom: "p1_e9_purch_total_py" },
  { type: "pct", outputId: "calc_p1_e9_purch_top10_pct_cy", num: "p1_e9_purch_top10_cy", denom: "p1_e9_purch_total_th_cy" },
  { type: "pct", outputId: "calc_p1_e9_purch_top10_pct_py", num: "p1_e9_purch_top10_py", denom: "p1_e9_purch_total_th_py" },
  { type: "pct", outputId: "calc_p1_e9_sales_pct_cy", num: "p1_e9_sales_i_cy", denom: "p1_e9_sales_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_sales_pct_py", num: "p1_e9_sales_i_py", denom: "p1_e9_sales_total_py" },
  { type: "pct", outputId: "calc_p1_e9_sales_top10_pct_cy", num: "p1_e9_sales_top10_cy", denom: "p1_e9_sales_total_dd_cy" },
  { type: "pct", outputId: "calc_p1_e9_sales_top10_pct_py", num: "p1_e9_sales_top10_py", denom: "p1_e9_sales_total_dd_py" },
  { type: "pct", outputId: "calc_p1_e9_rpt_purch_cy", num: "p1_e9_rpt_purch_i_cy", denom: "p1_e9_rpt_purch_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_rpt_purch_py", num: "p1_e9_rpt_purch_i_py", denom: "p1_e9_rpt_purch_total_py" },
  { type: "pct", outputId: "calc_p1_e9_rpt_sales_cy", num: "p1_e9_rpt_sales_i_cy", denom: "p1_e9_rpt_sales_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_rpt_sales_py", num: "p1_e9_rpt_sales_i_py", denom: "p1_e9_rpt_sales_total_py" },
  { type: "pct", outputId: "calc_p1_e9_rpt_loans_cy", num: "p1_e9_rpt_loans_i_cy", denom: "p1_e9_rpt_loans_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_rpt_loans_py", num: "p1_e9_rpt_loans_i_py", denom: "p1_e9_rpt_loans_total_py" },
  { type: "pct", outputId: "calc_p1_e9_rpt_inv_cy", num: "p1_e9_rpt_inv_i_cy", denom: "p1_e9_rpt_inv_total_cy" },
  { type: "pct", outputId: "calc_p1_e9_rpt_inv_py", num: "p1_e9_rpt_inv_i_py", denom: "p1_e9_rpt_inv_total_py" },
  // P3 – Q1 well-being: sum for Total row, then pct (benefit No. / Total A)
  ...["e1a_perm", "e1a_oth", "e1b_perm", "e1b_oth"].flatMap((pre) => {
    const p = `p3_${pre}`;
    const sumRules: CalcRule[] = [
      { type: "sum", outputId: `calc_${p}_tot_t`, sumIds: [`${p}_m_t`, `${p}_f_t`, `${p}_o_t`], decimals: 0 },
      { type: "sum", outputId: `calc_${p}_tot_hi`, sumIds: [`${p}_m_hi`, `${p}_f_hi`, `${p}_o_hi`], decimals: 0 },
      { type: "sum", outputId: `calc_${p}_tot_ac`, sumIds: [`${p}_m_ac`, `${p}_f_ac`, `${p}_o_ac`], decimals: 0 },
      { type: "sum", outputId: `calc_${p}_tot_mat`, sumIds: [`${p}_m_mat`, `${p}_f_mat`, `${p}_o_mat`], decimals: 0 },
      { type: "sum", outputId: `calc_${p}_tot_pat`, sumIds: [`${p}_m_pat`, `${p}_f_pat`, `${p}_o_pat`], decimals: 0 },
      { type: "sum", outputId: `calc_${p}_tot_dc`, sumIds: [`${p}_m_dc`, `${p}_f_dc`, `${p}_o_dc`], decimals: 0 },
    ];
    const pctRules: CalcRule[] = [
      { type: "pct", outputId: `calc_${p}_m_hi_pct`, num: `${p}_m_hi`, denom: `${p}_m_t` },
      { type: "pct", outputId: `calc_${p}_m_ac_pct`, num: `${p}_m_ac`, denom: `${p}_m_t` },
      { type: "pct", outputId: `calc_${p}_m_mat_pct`, num: `${p}_m_mat`, denom: `${p}_m_t` },
      { type: "pct", outputId: `calc_${p}_m_pat_pct`, num: `${p}_m_pat`, denom: `${p}_m_t` },
      { type: "pct", outputId: `calc_${p}_m_dc_pct`, num: `${p}_m_dc`, denom: `${p}_m_t` },
      { type: "pct", outputId: `calc_${p}_f_hi_pct`, num: `${p}_f_hi`, denom: `${p}_f_t` },
      { type: "pct", outputId: `calc_${p}_f_ac_pct`, num: `${p}_f_ac`, denom: `${p}_f_t` },
      { type: "pct", outputId: `calc_${p}_f_mat_pct`, num: `${p}_f_mat`, denom: `${p}_f_t` },
      { type: "pct", outputId: `calc_${p}_f_pat_pct`, num: `${p}_f_pat`, denom: `${p}_f_t` },
      { type: "pct", outputId: `calc_${p}_f_dc_pct`, num: `${p}_f_dc`, denom: `${p}_f_t` },
      { type: "pct", outputId: `calc_${p}_o_hi_pct`, num: `${p}_o_hi`, denom: `${p}_o_t` },
      { type: "pct", outputId: `calc_${p}_o_ac_pct`, num: `${p}_o_ac`, denom: `${p}_o_t` },
      { type: "pct", outputId: `calc_${p}_o_mat_pct`, num: `${p}_o_mat`, denom: `${p}_o_t` },
      { type: "pct", outputId: `calc_${p}_o_pat_pct`, num: `${p}_o_pat`, denom: `${p}_o_t` },
      { type: "pct", outputId: `calc_${p}_o_dc_pct`, num: `${p}_o_dc`, denom: `${p}_o_t` },
      { type: "pct", outputId: `calc_${p}_tot_hi_pct`, num: `calc_${p}_tot_hi`, denom: `calc_${p}_tot_t` },
      { type: "pct", outputId: `calc_${p}_tot_ac_pct`, num: `calc_${p}_tot_ac`, denom: `calc_${p}_tot_t` },
      { type: "pct", outputId: `calc_${p}_tot_mat_pct`, num: `calc_${p}_tot_mat`, denom: `calc_${p}_tot_t` },
      { type: "pct", outputId: `calc_${p}_tot_pat_pct`, num: `calc_${p}_tot_pat`, denom: `calc_${p}_tot_t` },
      { type: "pct", outputId: `calc_${p}_tot_dc_pct`, num: `calc_${p}_tot_dc`, denom: `calc_${p}_tot_t` },
    ];
    return [...sumRules, ...pctRules];
  }),
  { type: "pct", outputId: "calc_p3_e1c_cy_pct", num: "p3_e1c_cy_spend", denom: "p3_e1c_cy_rev" },
  { type: "pct", outputId: "calc_p3_e1c_py_pct", num: "p3_e1c_py_spend", denom: "p3_e1c_py_rev" },
  // P3 – Q7 membership (emp, wrk × m,f,o × cy,py)
  { type: "pct", outputId: "calc_p3_e7_emp_m_cy", num: "p3_e7_emp_m_u_cy", denom: "p3_e7_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_emp_m_py", num: "p3_e7_emp_m_u_py", denom: "p3_e7_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_e7_emp_f_cy", num: "p3_e7_emp_f_u_cy", denom: "p3_e7_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_emp_f_py", num: "p3_e7_emp_f_u_py", denom: "p3_e7_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_e7_emp_o_cy", num: "p3_e7_emp_o_u_cy", denom: "p3_e7_emp_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_emp_o_py", num: "p3_e7_emp_o_u_py", denom: "p3_e7_emp_o_t_py" },
  { type: "pct", outputId: "calc_p3_e7_wrk_m_cy", num: "p3_e7_wrk_m_u_cy", denom: "p3_e7_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_wrk_m_py", num: "p3_e7_wrk_m_u_py", denom: "p3_e7_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_e7_wrk_f_cy", num: "p3_e7_wrk_f_u_cy", denom: "p3_e7_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_wrk_f_py", num: "p3_e7_wrk_f_u_py", denom: "p3_e7_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_e7_wrk_o_cy", num: "p3_e7_wrk_o_u_cy", denom: "p3_e7_wrk_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_wrk_o_py", num: "p3_e7_wrk_o_u_py", denom: "p3_e7_wrk_o_t_py" },
  // P3 – Q7 Total row (m+f+o)
  { type: "sum", outputId: "calc_p3_e7_emp_tot_t_cy", sumIds: ["p3_e7_emp_m_t_cy", "p3_e7_emp_f_t_cy", "p3_e7_emp_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_emp_tot_t_py", sumIds: ["p3_e7_emp_m_t_py", "p3_e7_emp_f_t_py", "p3_e7_emp_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_emp_tot_u_cy", sumIds: ["p3_e7_emp_m_u_cy", "p3_e7_emp_f_u_cy", "p3_e7_emp_o_u_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_emp_tot_u_py", sumIds: ["p3_e7_emp_m_u_py", "p3_e7_emp_f_u_py", "p3_e7_emp_o_u_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e7_emp_tot_cy", num: "calc_p3_e7_emp_tot_u_cy", denom: "calc_p3_e7_emp_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_emp_tot_py", num: "calc_p3_e7_emp_tot_u_py", denom: "calc_p3_e7_emp_tot_t_py" },
  { type: "sum", outputId: "calc_p3_e7_wrk_tot_t_cy", sumIds: ["p3_e7_wrk_m_t_cy", "p3_e7_wrk_f_t_cy", "p3_e7_wrk_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_wrk_tot_t_py", sumIds: ["p3_e7_wrk_m_t_py", "p3_e7_wrk_f_t_py", "p3_e7_wrk_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_wrk_tot_u_cy", sumIds: ["p3_e7_wrk_m_u_cy", "p3_e7_wrk_f_u_cy", "p3_e7_wrk_o_u_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e7_wrk_tot_u_py", sumIds: ["p3_e7_wrk_m_u_py", "p3_e7_wrk_f_u_py", "p3_e7_wrk_o_u_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e7_wrk_tot_cy", num: "calc_p3_e7_wrk_tot_u_cy", denom: "calc_p3_e7_wrk_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e7_wrk_tot_py", num: "calc_p3_e7_wrk_tot_u_py", denom: "calc_p3_e7_wrk_tot_t_py" },
  // P3 – Q8 training (emp, wrk × m,f,o × hs,sk × cy,py)
  { type: "pct", outputId: "calc_p3_e8_emp_m_hs_cy", num: "p3_e8_emp_m_hs_cy", denom: "p3_e8_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_m_sk_cy", num: "p3_e8_emp_m_sk_cy", denom: "p3_e8_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_m_hs_py", num: "p3_e8_emp_m_hs_py", denom: "p3_e8_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_m_sk_py", num: "p3_e8_emp_m_sk_py", denom: "p3_e8_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_f_hs_cy", num: "p3_e8_emp_f_hs_cy", denom: "p3_e8_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_f_sk_cy", num: "p3_e8_emp_f_sk_cy", denom: "p3_e8_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_f_hs_py", num: "p3_e8_emp_f_hs_py", denom: "p3_e8_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_f_sk_py", num: "p3_e8_emp_f_sk_py", denom: "p3_e8_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_o_hs_cy", num: "p3_e8_emp_o_hs_cy", denom: "p3_e8_emp_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_o_sk_cy", num: "p3_e8_emp_o_sk_cy", denom: "p3_e8_emp_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_o_hs_py", num: "p3_e8_emp_o_hs_py", denom: "p3_e8_emp_o_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_o_sk_py", num: "p3_e8_emp_o_sk_py", denom: "p3_e8_emp_o_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_m_hs_cy", num: "p3_e8_wrk_m_hs_cy", denom: "p3_e8_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_m_sk_cy", num: "p3_e8_wrk_m_sk_cy", denom: "p3_e8_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_m_hs_py", num: "p3_e8_wrk_m_hs_py", denom: "p3_e8_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_m_sk_py", num: "p3_e8_wrk_m_sk_py", denom: "p3_e8_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_f_hs_cy", num: "p3_e8_wrk_f_hs_cy", denom: "p3_e8_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_f_sk_cy", num: "p3_e8_wrk_f_sk_cy", denom: "p3_e8_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_f_hs_py", num: "p3_e8_wrk_f_hs_py", denom: "p3_e8_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_f_sk_py", num: "p3_e8_wrk_f_sk_py", denom: "p3_e8_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_o_hs_cy", num: "p3_e8_wrk_o_hs_cy", denom: "p3_e8_wrk_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_o_sk_cy", num: "p3_e8_wrk_o_sk_cy", denom: "p3_e8_wrk_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_o_hs_py", num: "p3_e8_wrk_o_hs_py", denom: "p3_e8_wrk_o_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_o_sk_py", num: "p3_e8_wrk_o_sk_py", denom: "p3_e8_wrk_o_t_py" },
  // P3 – Q8 Total row (m+f+o)
  { type: "sum", outputId: "calc_p3_e8_emp_tot_t_cy", sumIds: ["p3_e8_emp_m_t_cy", "p3_e8_emp_f_t_cy", "p3_e8_emp_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_emp_tot_t_py", sumIds: ["p3_e8_emp_m_t_py", "p3_e8_emp_f_t_py", "p3_e8_emp_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_emp_tot_hs_cy", sumIds: ["p3_e8_emp_m_hs_cy", "p3_e8_emp_f_hs_cy", "p3_e8_emp_o_hs_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_emp_tot_hs_py", sumIds: ["p3_e8_emp_m_hs_py", "p3_e8_emp_f_hs_py", "p3_e8_emp_o_hs_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_emp_tot_sk_cy", sumIds: ["p3_e8_emp_m_sk_cy", "p3_e8_emp_f_sk_cy", "p3_e8_emp_o_sk_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_emp_tot_sk_py", sumIds: ["p3_e8_emp_m_sk_py", "p3_e8_emp_f_sk_py", "p3_e8_emp_o_sk_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e8_emp_tot_hs_cy_pct", num: "calc_p3_e8_emp_tot_hs_cy", denom: "calc_p3_e8_emp_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_tot_hs_py_pct", num: "calc_p3_e8_emp_tot_hs_py", denom: "calc_p3_e8_emp_tot_t_py" },
  { type: "pct", outputId: "calc_p3_e8_emp_tot_sk_cy_pct", num: "calc_p3_e8_emp_tot_sk_cy", denom: "calc_p3_e8_emp_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_emp_tot_sk_py_pct", num: "calc_p3_e8_emp_tot_sk_py", denom: "calc_p3_e8_emp_tot_t_py" },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_t_cy", sumIds: ["p3_e8_wrk_m_t_cy", "p3_e8_wrk_f_t_cy", "p3_e8_wrk_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_t_py", sumIds: ["p3_e8_wrk_m_t_py", "p3_e8_wrk_f_t_py", "p3_e8_wrk_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_hs_cy", sumIds: ["p3_e8_wrk_m_hs_cy", "p3_e8_wrk_f_hs_cy", "p3_e8_wrk_o_hs_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_hs_py", sumIds: ["p3_e8_wrk_m_hs_py", "p3_e8_wrk_f_hs_py", "p3_e8_wrk_o_hs_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_sk_cy", sumIds: ["p3_e8_wrk_m_sk_cy", "p3_e8_wrk_f_sk_cy", "p3_e8_wrk_o_sk_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e8_wrk_tot_sk_py", sumIds: ["p3_e8_wrk_m_sk_py", "p3_e8_wrk_f_sk_py", "p3_e8_wrk_o_sk_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e8_wrk_tot_hs_cy_pct", num: "calc_p3_e8_wrk_tot_hs_cy", denom: "calc_p3_e8_wrk_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_tot_hs_py_pct", num: "calc_p3_e8_wrk_tot_hs_py", denom: "calc_p3_e8_wrk_tot_t_py" },
  { type: "pct", outputId: "calc_p3_e8_wrk_tot_sk_cy_pct", num: "calc_p3_e8_wrk_tot_sk_cy", denom: "calc_p3_e8_wrk_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e8_wrk_tot_sk_py_pct", num: "calc_p3_e8_wrk_tot_sk_py", denom: "calc_p3_e8_wrk_tot_t_py" },
  // P3 – Q9 performance reviews (emp, wrk × m,f,o × cy,py)
  { type: "pct", outputId: "calc_p3_e9_emp_m_cy", num: "p3_e9_emp_m_r_cy", denom: "p3_e9_emp_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_emp_m_py", num: "p3_e9_emp_m_r_py", denom: "p3_e9_emp_m_t_py" },
  { type: "pct", outputId: "calc_p3_e9_emp_f_cy", num: "p3_e9_emp_f_r_cy", denom: "p3_e9_emp_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_emp_f_py", num: "p3_e9_emp_f_r_py", denom: "p3_e9_emp_f_t_py" },
  { type: "pct", outputId: "calc_p3_e9_emp_o_cy", num: "p3_e9_emp_o_r_cy", denom: "p3_e9_emp_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_emp_o_py", num: "p3_e9_emp_o_r_py", denom: "p3_e9_emp_o_t_py" },
  { type: "pct", outputId: "calc_p3_e9_wrk_m_cy", num: "p3_e9_wrk_m_r_cy", denom: "p3_e9_wrk_m_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_wrk_m_py", num: "p3_e9_wrk_m_r_py", denom: "p3_e9_wrk_m_t_py" },
  { type: "pct", outputId: "calc_p3_e9_wrk_f_cy", num: "p3_e9_wrk_f_r_cy", denom: "p3_e9_wrk_f_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_wrk_f_py", num: "p3_e9_wrk_f_r_py", denom: "p3_e9_wrk_f_t_py" },
  { type: "pct", outputId: "calc_p3_e9_wrk_o_cy", num: "p3_e9_wrk_o_r_cy", denom: "p3_e9_wrk_o_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_wrk_o_py", num: "p3_e9_wrk_o_r_py", denom: "p3_e9_wrk_o_t_py" },
  // P3 – Q9 Total row (m+f+o)
  { type: "sum", outputId: "calc_p3_e9_emp_tot_t_cy", sumIds: ["p3_e9_emp_m_t_cy", "p3_e9_emp_f_t_cy", "p3_e9_emp_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_emp_tot_t_py", sumIds: ["p3_e9_emp_m_t_py", "p3_e9_emp_f_t_py", "p3_e9_emp_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_emp_tot_r_cy", sumIds: ["p3_e9_emp_m_r_cy", "p3_e9_emp_f_r_cy", "p3_e9_emp_o_r_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_emp_tot_r_py", sumIds: ["p3_e9_emp_m_r_py", "p3_e9_emp_f_r_py", "p3_e9_emp_o_r_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e9_emp_tot_cy", num: "calc_p3_e9_emp_tot_r_cy", denom: "calc_p3_e9_emp_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_emp_tot_py", num: "calc_p3_e9_emp_tot_r_py", denom: "calc_p3_e9_emp_tot_t_py" },
  { type: "sum", outputId: "calc_p3_e9_wrk_tot_t_cy", sumIds: ["p3_e9_wrk_m_t_cy", "p3_e9_wrk_f_t_cy", "p3_e9_wrk_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_wrk_tot_t_py", sumIds: ["p3_e9_wrk_m_t_py", "p3_e9_wrk_f_t_py", "p3_e9_wrk_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_wrk_tot_r_cy", sumIds: ["p3_e9_wrk_m_r_cy", "p3_e9_wrk_f_r_cy", "p3_e9_wrk_o_r_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p3_e9_wrk_tot_r_py", sumIds: ["p3_e9_wrk_m_r_py", "p3_e9_wrk_f_r_py", "p3_e9_wrk_o_r_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p3_e9_wrk_tot_cy", num: "calc_p3_e9_wrk_tot_r_cy", denom: "calc_p3_e9_wrk_tot_t_cy" },
  { type: "pct", outputId: "calc_p3_e9_wrk_tot_py", num: "calc_p3_e9_wrk_tot_r_py", denom: "calc_p3_e9_wrk_tot_t_py" },
  // P5 – human rights training + pay equity + complaints
  { type: "pct", outputId: "calc_p5_pct_1", num: "p5_e1_emp_perm_c_cy", denom: "p5_e1_emp_perm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_2", num: "p5_e1_emp_perm_c_py", denom: "p5_e1_emp_perm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_3", num: "p5_e1_emp_oth_c_cy", denom: "p5_e1_emp_oth_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_4", num: "p5_e1_emp_oth_c_py", denom: "p5_e1_emp_oth_t_py" },
  { type: "pct", outputId: "calc_p5_pct_5", num: "p5_e1_wrk_perm_c_cy", denom: "p5_e1_wrk_perm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_6", num: "p5_e1_wrk_perm_c_py", denom: "p5_e1_wrk_perm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_7", num: "p5_e1_wrk_oth_c_cy", denom: "p5_e1_wrk_oth_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_8", num: "p5_e1_wrk_oth_c_py", denom: "p5_e1_wrk_oth_t_py" },
  // Q1 Total Employees / Workers (sum perm + oth)
  { type: "sum", outputId: "calc_p5_e1_emp_tot_t_cy", sumIds: ["p5_e1_emp_perm_t_cy", "p5_e1_emp_oth_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_emp_tot_t_py", sumIds: ["p5_e1_emp_perm_t_py", "p5_e1_emp_oth_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_emp_tot_c_cy", sumIds: ["p5_e1_emp_perm_c_cy", "p5_e1_emp_oth_c_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_emp_tot_c_py", sumIds: ["p5_e1_emp_perm_c_py", "p5_e1_emp_oth_c_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_wrk_tot_t_cy", sumIds: ["p5_e1_wrk_perm_t_cy", "p5_e1_wrk_oth_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_wrk_tot_t_py", sumIds: ["p5_e1_wrk_perm_t_py", "p5_e1_wrk_oth_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_wrk_tot_c_cy", sumIds: ["p5_e1_wrk_perm_c_cy", "p5_e1_wrk_oth_c_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e1_wrk_tot_c_py", sumIds: ["p5_e1_wrk_perm_c_py", "p5_e1_wrk_oth_c_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p5_e1_emp_tot_pct_cy", num: "calc_p5_e1_emp_tot_c_cy", denom: "calc_p5_e1_emp_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e1_emp_tot_pct_py", num: "calc_p5_e1_emp_tot_c_py", denom: "calc_p5_e1_emp_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e1_wrk_tot_pct_cy", num: "calc_p5_e1_wrk_tot_c_cy", denom: "calc_p5_e1_wrk_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e1_wrk_tot_pct_py", num: "calc_p5_e1_wrk_tot_c_py", denom: "calc_p5_e1_wrk_tot_t_py" },
  { type: "pct", outputId: "calc_p5_pct_9", num: "p5_e2_emp_pm_eq_cy", denom: "p5_e2_emp_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_10", num: "p5_e2_emp_pm_more_cy", denom: "p5_e2_emp_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_11", num: "p5_e2_emp_pm_eq_py", denom: "p5_e2_emp_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_12", num: "p5_e2_emp_pm_more_py", denom: "p5_e2_emp_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_13", num: "p5_e2_emp_pf_eq_cy", denom: "p5_e2_emp_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_14", num: "p5_e2_emp_pf_more_cy", denom: "p5_e2_emp_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_15", num: "p5_e2_emp_pf_eq_py", denom: "p5_e2_emp_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_16", num: "p5_e2_emp_pf_more_py", denom: "p5_e2_emp_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_17", num: "p5_e2_wrk_pm_eq_cy", denom: "p5_e2_wrk_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_18", num: "p5_e2_wrk_pm_more_cy", denom: "p5_e2_wrk_pm_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_19", num: "p5_e2_wrk_pm_eq_py", denom: "p5_e2_wrk_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_20", num: "p5_e2_wrk_pm_more_py", denom: "p5_e2_wrk_pm_t_py" },
  { type: "pct", outputId: "calc_p5_pct_21", num: "p5_e2_wrk_pf_eq_cy", denom: "p5_e2_wrk_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_22", num: "p5_e2_wrk_pf_more_cy", denom: "p5_e2_wrk_pf_t_cy" },
  { type: "pct", outputId: "calc_p5_pct_23", num: "p5_e2_wrk_pf_eq_py", denom: "p5_e2_wrk_pf_t_py" },
  { type: "pct", outputId: "calc_p5_pct_24", num: "p5_e2_wrk_pf_more_py", denom: "p5_e2_wrk_pf_t_py" },
  // Q2 – emp_po, emp_otp_*, wrk_po, wrk_otp_*
  { type: "pct", outputId: "calc_p5_e2_emp_po_eq_cy", num: "p5_e2_emp_po_eq_cy", denom: "p5_e2_emp_po_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_po_more_cy", num: "p5_e2_emp_po_more_cy", denom: "p5_e2_emp_po_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_po_eq_py", num: "p5_e2_emp_po_eq_py", denom: "p5_e2_emp_po_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_po_more_py", num: "p5_e2_emp_po_more_py", denom: "p5_e2_emp_po_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_m_eq_cy", num: "p5_e2_emp_otp_m_eq_cy", denom: "p5_e2_emp_otp_m_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_m_more_cy", num: "p5_e2_emp_otp_m_more_cy", denom: "p5_e2_emp_otp_m_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_m_eq_py", num: "p5_e2_emp_otp_m_eq_py", denom: "p5_e2_emp_otp_m_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_m_more_py", num: "p5_e2_emp_otp_m_more_py", denom: "p5_e2_emp_otp_m_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_f_eq_cy", num: "p5_e2_emp_otp_f_eq_cy", denom: "p5_e2_emp_otp_f_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_f_more_cy", num: "p5_e2_emp_otp_f_more_cy", denom: "p5_e2_emp_otp_f_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_f_eq_py", num: "p5_e2_emp_otp_f_eq_py", denom: "p5_e2_emp_otp_f_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_f_more_py", num: "p5_e2_emp_otp_f_more_py", denom: "p5_e2_emp_otp_f_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_o_eq_cy", num: "p5_e2_emp_otp_o_eq_cy", denom: "p5_e2_emp_otp_o_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_o_more_cy", num: "p5_e2_emp_otp_o_more_cy", denom: "p5_e2_emp_otp_o_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_o_eq_py", num: "p5_e2_emp_otp_o_eq_py", denom: "p5_e2_emp_otp_o_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_o_more_py", num: "p5_e2_emp_otp_o_more_py", denom: "p5_e2_emp_otp_o_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_po_eq_cy", num: "p5_e2_wrk_po_eq_cy", denom: "p5_e2_wrk_po_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_po_more_cy", num: "p5_e2_wrk_po_more_cy", denom: "p5_e2_wrk_po_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_po_eq_py", num: "p5_e2_wrk_po_eq_py", denom: "p5_e2_wrk_po_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_po_more_py", num: "p5_e2_wrk_po_more_py", denom: "p5_e2_wrk_po_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_m_eq_cy", num: "p5_e2_wrk_otp_m_eq_cy", denom: "p5_e2_wrk_otp_m_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_m_more_cy", num: "p5_e2_wrk_otp_m_more_cy", denom: "p5_e2_wrk_otp_m_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_m_eq_py", num: "p5_e2_wrk_otp_m_eq_py", denom: "p5_e2_wrk_otp_m_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_m_more_py", num: "p5_e2_wrk_otp_m_more_py", denom: "p5_e2_wrk_otp_m_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_f_eq_cy", num: "p5_e2_wrk_otp_f_eq_cy", denom: "p5_e2_wrk_otp_f_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_f_more_cy", num: "p5_e2_wrk_otp_f_more_cy", denom: "p5_e2_wrk_otp_f_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_f_eq_py", num: "p5_e2_wrk_otp_f_eq_py", denom: "p5_e2_wrk_otp_f_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_f_more_py", num: "p5_e2_wrk_otp_f_more_py", denom: "p5_e2_wrk_otp_f_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_o_eq_cy", num: "p5_e2_wrk_otp_o_eq_cy", denom: "p5_e2_wrk_otp_o_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_o_more_cy", num: "p5_e2_wrk_otp_o_more_cy", denom: "p5_e2_wrk_otp_o_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_o_eq_py", num: "p5_e2_wrk_otp_o_eq_py", denom: "p5_e2_wrk_otp_o_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_o_more_py", num: "p5_e2_wrk_otp_o_more_py", denom: "p5_e2_wrk_otp_o_t_py" },
  // Q2 – Total Permanent, Total OTP (sum + pct)
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_t_cy", sumIds: ["p5_e2_emp_pm_t_cy", "p5_e2_emp_pf_t_cy", "p5_e2_emp_po_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_t_py", sumIds: ["p5_e2_emp_pm_t_py", "p5_e2_emp_pf_t_py", "p5_e2_emp_po_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_eq_cy", sumIds: ["p5_e2_emp_pm_eq_cy", "p5_e2_emp_pf_eq_cy", "p5_e2_emp_po_eq_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_eq_py", sumIds: ["p5_e2_emp_pm_eq_py", "p5_e2_emp_pf_eq_py", "p5_e2_emp_po_eq_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_more_cy", sumIds: ["p5_e2_emp_pm_more_cy", "p5_e2_emp_pf_more_cy", "p5_e2_emp_po_more_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_perm_tot_more_py", sumIds: ["p5_e2_emp_pm_more_py", "p5_e2_emp_pf_more_py", "p5_e2_emp_po_more_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_t_cy", sumIds: ["p5_e2_emp_otp_m_t_cy", "p5_e2_emp_otp_f_t_cy", "p5_e2_emp_otp_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_t_py", sumIds: ["p5_e2_emp_otp_m_t_py", "p5_e2_emp_otp_f_t_py", "p5_e2_emp_otp_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_eq_cy", sumIds: ["p5_e2_emp_otp_m_eq_cy", "p5_e2_emp_otp_f_eq_cy", "p5_e2_emp_otp_o_eq_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_eq_py", sumIds: ["p5_e2_emp_otp_m_eq_py", "p5_e2_emp_otp_f_eq_py", "p5_e2_emp_otp_o_eq_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_more_cy", sumIds: ["p5_e2_emp_otp_m_more_cy", "p5_e2_emp_otp_f_more_cy", "p5_e2_emp_otp_o_more_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_emp_otp_tot_more_py", sumIds: ["p5_e2_emp_otp_m_more_py", "p5_e2_emp_otp_f_more_py", "p5_e2_emp_otp_o_more_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_t_cy", sumIds: ["p5_e2_wrk_pm_t_cy", "p5_e2_wrk_pf_t_cy", "p5_e2_wrk_po_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_t_py", sumIds: ["p5_e2_wrk_pm_t_py", "p5_e2_wrk_pf_t_py", "p5_e2_wrk_po_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_eq_cy", sumIds: ["p5_e2_wrk_pm_eq_cy", "p5_e2_wrk_pf_eq_cy", "p5_e2_wrk_po_eq_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_eq_py", sumIds: ["p5_e2_wrk_pm_eq_py", "p5_e2_wrk_pf_eq_py", "p5_e2_wrk_po_eq_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_more_cy", sumIds: ["p5_e2_wrk_pm_more_cy", "p5_e2_wrk_pf_more_cy", "p5_e2_wrk_po_more_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_perm_tot_more_py", sumIds: ["p5_e2_wrk_pm_more_py", "p5_e2_wrk_pf_more_py", "p5_e2_wrk_po_more_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_t_cy", sumIds: ["p5_e2_wrk_otp_m_t_cy", "p5_e2_wrk_otp_f_t_cy", "p5_e2_wrk_otp_o_t_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_t_py", sumIds: ["p5_e2_wrk_otp_m_t_py", "p5_e2_wrk_otp_f_t_py", "p5_e2_wrk_otp_o_t_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_eq_cy", sumIds: ["p5_e2_wrk_otp_m_eq_cy", "p5_e2_wrk_otp_f_eq_cy", "p5_e2_wrk_otp_o_eq_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_eq_py", sumIds: ["p5_e2_wrk_otp_m_eq_py", "p5_e2_wrk_otp_f_eq_py", "p5_e2_wrk_otp_o_eq_py"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_more_cy", sumIds: ["p5_e2_wrk_otp_m_more_cy", "p5_e2_wrk_otp_f_more_cy", "p5_e2_wrk_otp_o_more_cy"], decimals: 0 },
  { type: "sum", outputId: "calc_p5_e2_wrk_otp_tot_more_py", sumIds: ["p5_e2_wrk_otp_m_more_py", "p5_e2_wrk_otp_f_more_py", "p5_e2_wrk_otp_o_more_py"], decimals: 0 },
  { type: "pct", outputId: "calc_p5_e2_emp_perm_tot_eq_pct_cy", num: "calc_p5_e2_emp_perm_tot_eq_cy", denom: "calc_p5_e2_emp_perm_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_perm_tot_more_pct_cy", num: "calc_p5_e2_emp_perm_tot_more_cy", denom: "calc_p5_e2_emp_perm_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_perm_tot_eq_pct_py", num: "calc_p5_e2_emp_perm_tot_eq_py", denom: "calc_p5_e2_emp_perm_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_perm_tot_more_pct_py", num: "calc_p5_e2_emp_perm_tot_more_py", denom: "calc_p5_e2_emp_perm_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_tot_eq_pct_cy", num: "calc_p5_e2_emp_otp_tot_eq_cy", denom: "calc_p5_e2_emp_otp_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_tot_more_pct_cy", num: "calc_p5_e2_emp_otp_tot_more_cy", denom: "calc_p5_e2_emp_otp_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_tot_eq_pct_py", num: "calc_p5_e2_emp_otp_tot_eq_py", denom: "calc_p5_e2_emp_otp_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_emp_otp_tot_more_pct_py", num: "calc_p5_e2_emp_otp_tot_more_py", denom: "calc_p5_e2_emp_otp_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_perm_tot_eq_pct_cy", num: "calc_p5_e2_wrk_perm_tot_eq_cy", denom: "calc_p5_e2_wrk_perm_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_perm_tot_more_pct_cy", num: "calc_p5_e2_wrk_perm_tot_more_cy", denom: "calc_p5_e2_wrk_perm_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_perm_tot_eq_pct_py", num: "calc_p5_e2_wrk_perm_tot_eq_py", denom: "calc_p5_e2_wrk_perm_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_perm_tot_more_pct_py", num: "calc_p5_e2_wrk_perm_tot_more_py", denom: "calc_p5_e2_wrk_perm_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_tot_eq_pct_cy", num: "calc_p5_e2_wrk_otp_tot_eq_cy", denom: "calc_p5_e2_wrk_otp_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_tot_more_pct_cy", num: "calc_p5_e2_wrk_otp_tot_more_cy", denom: "calc_p5_e2_wrk_otp_tot_t_cy" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_tot_eq_pct_py", num: "calc_p5_e2_wrk_otp_tot_eq_py", denom: "calc_p5_e2_wrk_otp_tot_t_py" },
  { type: "pct", outputId: "calc_p5_e2_wrk_otp_tot_more_pct_py", num: "calc_p5_e2_wrk_otp_tot_more_py", denom: "calc_p5_e2_wrk_otp_tot_t_py" },
  { type: "pct", outputId: "calc_p5_pct_25", num: "p5_e3b_cy_f", denom: "p5_e3b_cy_t" },
  { type: "pct", outputId: "calc_p5_pct_26", num: "p5_e3b_py_f", denom: "p5_e3b_py_t" },
  { type: "pct", outputId: "calc_p5_pct_27", num: "p5_e7_tot_cy", denom: "p5_e7_f_cy" },
  { type: "pct", outputId: "calc_p5_pct_28", num: "p5_e7_tot_py", denom: "p5_e7_f_py" },
  // P8 – geographic beneficiary percentages
  { type: "pct", outputId: "calc_p8_pct_1", num: "p8_e5_rural_w_cy", denom: "p8_e5_rural_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_2", num: "p8_e5_rural_w_py", denom: "p8_e5_rural_t_py" },
  { type: "pct", outputId: "calc_p8_pct_3", num: "p8_e5_semi_w_cy", denom: "p8_e5_semi_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_4", num: "p8_e5_semi_w_py", denom: "p8_e5_semi_t_py" },
  { type: "pct", outputId: "calc_p8_pct_5", num: "p8_e5_urb_w_cy", denom: "p8_e5_urb_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_6", num: "p8_e5_urb_w_py", denom: "p8_e5_urb_t_py" },
  { type: "pct", outputId: "calc_p8_pct_7", num: "p8_e5_metro_w_cy", denom: "p8_e5_metro_t_cy" },
  { type: "pct", outputId: "calc_p8_pct_8", num: "p8_e5_metro_w_py", denom: "p8_e5_metro_t_py" },
];
