-- Phase 2a: block-scoped collaboration (threads, comments, read receipts).
-- Hardened before first apply: block↔code map, poison-insert prevention,
-- admin-only resolve, authorship snapshots that survive user deletion.
--
-- Threads are one row per (org, reporting_year, assignment block). They store a
-- representative question_code (first code in the block) so RLS can reuse
-- can_access_question — the same gate as answers. panel_id / block_id are
-- denormalized for UI routing; the triple (block_id, panel_id, question_code)
-- must match brsr_assignment_blocks (enforced by FK + WITH CHECK).

-- ── Foundation: assignment-block map (source of truth for RLS binding) ───────

CREATE TABLE IF NOT EXISTS public.brsr_assignment_blocks (
  block_id TEXT PRIMARY KEY,
  panel_id TEXT NOT NULL,
  question_code TEXT NOT NULL
);

COMMENT ON TABLE public.brsr_assignment_blocks IS
  'Canonical block_id → panel_id + representative question_code. Keep in sync with lib/brsr/blockIndex.ts (scripts/generate-block-map.ts).';

COMMENT ON COLUMN public.brsr_assignment_blocks.question_code IS
  'First question_code in the assignment block; used by can_access_block / thread RLS.';

-- Generated by scripts/generate-block-map.ts (166 rows)
INSERT INTO public.brsr_assignment_blocks (block_id, panel_id, question_code)
VALUES
  ('generaldata_turnover_ppp', 'generaldata', 'gdata_turnover_cy'),
  ('generaldata_emp_worker', 'generaldata', 'gdata_emp_perm_m'),
  ('general_1', 'general', 'gen_1_cin'),
  ('general_2', 'general', 'gen_2_name'),
  ('general_3', 'general', 'gen_3_year_inc'),
  ('general_4', 'general', 'gen_4_registered_addr'),
  ('general_5', 'general', 'gen_5_corporate_addr'),
  ('general_6', 'general', 'gen_6_email'),
  ('general_7', 'general', 'gen_7_telephone'),
  ('general_8', 'general', 'gen_8_website'),
  ('general_9', 'general', 'gen_9_fy'),
  ('general_10', 'general', 'gen_10_row_count'),
  ('general_11', 'general', 'gen_11_paidup_capital'),
  ('general_12', 'general', 'gen_12_contact'),
  ('general_13', 'general', 'gen_13_boundary'),
  ('general_14', 'general', 'gen_14_row_count'),
  ('general_15', 'general', 'gen_15_assurance_type'),
  ('general_16', 'general', 'gen_16_1_main'),
  ('general_17', 'general', 'gen_17_1_product'),
  ('general_18', 'general', 'gen_18_nat_plants'),
  ('general_19', 'general', 'gen_19_nat_states'),
  ('general_19b', 'general', 'gen_19b_export_pct'),
  ('general_19c', 'general', 'gen_19c_customers'),
  ('general_20a', 'general', 'gen_20a_emp_perm_m'),
  ('general_20b', 'general', 'gen_20b_emp_perm_m'),
  ('general_21', 'general', 'gen_21_bod_total'),
  ('general_22', 'general', 'gen_22_emp_cy_m'),
  ('general_23', 'general', 'gen_23_1_name'),
  ('general_24', 'general', 'gen_24_csr_applicable'),
  ('general_25', 'general', 'gen_25_comm_mech'),
  ('general_26', 'general', 'gen_26_1_issue'),
  ('sectionb_1a', 'sectionb', 'sb_1a_p1'),
  ('sectionb_1b', 'sectionb', 'sb_1b_p1'),
  ('sectionb_1c', 'sectionb', 'sb_1c_p1'),
  ('sectionb_2', 'sectionb', 'sb_2_p1'),
  ('sectionb_3', 'sectionb', 'sb_3_p1'),
  ('sectionb_4', 'sectionb', 'sb_4_p1'),
  ('sectionb_5', 'sectionb', 'sb_5_p1'),
  ('sectionb_6', 'sectionb', 'sb_6_p1'),
  ('sectionb_7', 'sectionb', 'sb_7_statement'),
  ('sectionb_8', 'sectionb', 'sb_8_authority'),
  ('sectionb_9', 'sectionb', 'sb_9_p1'),
  ('sectionb_10a', 'sectionb', 'sb_10a_p1'),
  ('sectionb_10b', 'sectionb', 'sb_10b_p1'),
  ('sectionb_11', 'sectionb', 'sb_11_p1'),
  ('p1_1', 'p1', 'p1_e1_bod_prog'),
  ('p1_2', 'p1', 'p1_e2_pf_rowcount'),
  ('p1_3', 'p1', 'p1_e3_rowcount'),
  ('p1_4', 'p1', 'p1_e4_anticorr'),
  ('p1_5', 'p1', 'p1_e5_dir_cy'),
  ('p1_6', 'p1', 'p1_e6_dir_cy'),
  ('p1_7', 'p1', 'p1_e7_corrective'),
  ('p1_8', 'p1', 'p1_e8_ap_cy'),
  ('p1_9', 'p1', 'p1_e9_purch_i_cy'),
  ('p1_l1', 'p1', 'p1_l1_rowcount'),
  ('p1_l2', 'p1', 'p1_l2_conflict'),
  ('p1_notes', 'p1', 'p1_notes'),
  ('p2_1', 'p2', 'p2_e1_rd_cy'),
  ('p2_2', 'p2', 'p2_e2_yn'),
  ('p2_3', 'p2', 'p2_e3_plastics'),
  ('p2_4', 'p2', 'p2_e4_epr'),
  ('p2_l1', 'p2', 'p2_l1_yn'),
  ('p2_l2', 'p2', 'p2_l2_row0_product'),
  ('p2_l3', 'p2', 'p2_l3_row0_material'),
  ('p2_l4', 'p2', 'p2_l4_plast_cy_re'),
  ('p2_l5', 'p2', 'p2_l5_rowcount'),
  ('p2_notes', 'p2', 'p2_notes'),
  ('p3_1a', 'p3', 'p3_e1a_perm_m_t'),
  ('p3_1b', 'p3', 'p3_e1b_perm_m_t'),
  ('p3_1c', 'p3', 'p3_e1c_cy_spend'),
  ('p3_2', 'p3', 'p3_e2_pf_emp_cy'),
  ('p3_3', 'p3', 'p3_e3_access'),
  ('p3_4', 'p3', 'p3_e4_equal'),
  ('p3_5', 'p3', 'p3_e5_m_emp_ret'),
  ('p3_6', 'p3', 'p3_e6_yn'),
  ('p3_7', 'p3', 'p3_e7_emp_m_t_cy'),
  ('p3_8', 'p3', 'p3_e8_emp_m_t_cy'),
  ('p3_9', 'p3', 'p3_e9_emp_m_t_cy'),
  ('p3_10', 'p3', 'p3_e10_impl_yn'),
  ('p3_11', 'p3', 'p3_e11_ltifr_emp_cy'),
  ('p3_12', 'p3', 'p3_e12_measures'),
  ('p3_13', 'p3', 'p3_e13_wc_cy_f'),
  ('p3_14', 'p3', 'p3_e14_hs'),
  ('p3_15', 'p3', 'p3_e15_corrective'),
  ('p3_l1', 'p3', 'p3_l1_emp'),
  ('p3_l2', 'p3', 'p3_l2_statutory'),
  ('p3_l3', 'p3', 'p3_l3_emp_cy_t'),
  ('p3_l4', 'p3', 'p3_l4_transition'),
  ('p3_l5', 'p3', 'p3_l5_hs'),
  ('p3_l6', 'p3', 'p3_l6_corrective'),
  ('p3_notes', 'p3', 'p3_notes'),
  ('p4_1', 'p4', 'p4_e1_process'),
  ('p4_2', 'p4', 'p4_e2_row0_name'),
  ('p4_l1', 'p4', 'p4_l1_consult'),
  ('p4_l2', 'p4', 'p4_l2_yn'),
  ('p4_l3', 'p4', 'p4_l3_engagement'),
  ('p4_notes', 'p4', 'p4_notes'),
  ('p5_1', 'p5', 'p5_e1_emp_perm_t_cy'),
  ('p5_2', 'p5', 'p5_e2_emp_pm_t_cy'),
  ('p5_3a', 'p5', 'p5_e3a_bod_m_n'),
  ('p5_3b', 'p5', 'p5_e3b_cy_f'),
  ('p5_4', 'p5', 'p5_e4_focal'),
  ('p5_5', 'p5', 'p5_e5_mech'),
  ('p5_6', 'p5', 'p5_e6_sh_cy_f'),
  ('p5_7', 'p5', 'p5_e7_tot_cy'),
  ('p5_8', 'p5', 'p5_e8_mech'),
  ('p5_9', 'p5', 'p5_e9_contracts'),
  ('p5_10', 'p5', 'p5_e10_cl'),
  ('p5_11', 'p5', 'p5_e11_corrective'),
  ('p5_l1', 'p5', 'p5_l1_process'),
  ('p5_l2', 'p5', 'p5_l2_scope'),
  ('p5_l3', 'p5', 'p5_l3_access'),
  ('p5_l4', 'p5', 'p5_l4_sh'),
  ('p5_l5', 'p5', 'p5_l5_corrective'),
  ('p5_notes', 'p5', 'p5_notes'),
  ('p6_e1', 'p6', 'p6_e1_rev_cy'),
  ('p6_e2', 'p6', 'p6_e2_pat'),
  ('p6_e3', 'p6', 'p6_e3_rev_cy'),
  ('p6_e4', 'p6', 'p6_e4_sw_nt_cy'),
  ('p6_e5', 'p6', 'p6_e5_zld'),
  ('p6_e6', 'p6', 'p6_e6_applicable'),
  ('p6_e7', 'p6', 'p6_e7_rev_cy'),
  ('p6_e8', 'p6', 'p6_e8_ghg_yn'),
  ('p6_e9', 'p6', 'p6_e9_rev_cy'),
  ('p6_e10', 'p6', 'p6_e10_waste'),
  ('p6_e11', 'p6', 'p6_e11_rowcount'),
  ('p6_e12', 'p6', 'p6_e12_rowcount'),
  ('p6_e13', 'p6', 'p6_e13_comp'),
  ('p6_l1', 'p6', 'p6_l1_rowcount'),
  ('p6_l2', 'p6', 'p6_l2_applicable'),
  ('p6_l3', 'p6', 'p6_l3_bio'),
  ('p6_l4', 'p6', 'p6_l4_rowcount'),
  ('p6_l5', 'p6', 'p6_l5_yn'),
  ('p6_l6', 'p6', 'p6_l6_value'),
  ('p6_l7', 'p6', 'p6_l7_pct'),
  ('p6_l8', 'p6', 'p6_l8_generated'),
  ('p6_notes', 'p6', 'p6_notes'),
  ('p7_1a', 'p7', 'p7_e1a_count'),
  ('p7_1b', 'p7', 'p7_e1b_1_name'),
  ('p7_2', 'p7', 'p7_e2_auth'),
  ('p7_l1', 'p7', 'p7_l1_row0_policy'),
  ('p7_notes', 'p7', 'p7_notes'),
  ('p8_1', 'p8', 'p8_e1_name'),
  ('p8_2', 'p8', 'p8_e2_row0_name'),
  ('p8_3', 'p8', 'p8_e3_griev'),
  ('p8_4', 'p8', 'p8_e4_msme_cy'),
  ('p8_5', 'p8', 'p8_e5_rural_w_cy'),
  ('p8_l1', 'p8', 'p8_l1_impact'),
  ('p8_l2', 'p8', 'p8_l2_row0_state'),
  ('p8_l3', 'p8', 'p8_l3_yn'),
  ('p8_l4', 'p8', 'p8_l4_row0_ip'),
  ('p8_l5', 'p8', 'p8_l5_auth'),
  ('p8_l6', 'p8', 'p8_l6_row0_proj'),
  ('p8_notes', 'p8', 'p8_notes'),
  ('p9_1', 'p9', 'p9_e1_mech'),
  ('p9_2', 'p9', 'p9_e2_env'),
  ('p9_3', 'p9', 'p9_e3_dp_cy_f'),
  ('p9_4', 'p9', 'p9_e4_vol_num'),
  ('p9_5', 'p9', 'p9_e5_framework'),
  ('p9_6', 'p9', 'p9_e6_corrective'),
  ('p9_7', 'p9', 'p9_e7a_cy'),
  ('p9_l1', 'p9', 'p9_l1_channels'),
  ('p9_l2', 'p9', 'p9_l2_steps'),
  ('p9_l3', 'p9', 'p9_l3_mech'),
  ('p9_l4', 'p9', 'p9_l4_beyond'),
  ('p9_notes', 'p9', 'p9_notes')
ON CONFLICT (block_id) DO UPDATE SET
  panel_id = EXCLUDED.panel_id,
  question_code = EXCLUDED.question_code;

ALTER TABLE public.brsr_assignment_blocks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "brsr_assignment_blocks_select_authed"
  ON public.brsr_assignment_blocks;

CREATE POLICY "brsr_assignment_blocks_select_authed"
  ON public.brsr_assignment_blocks
  FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON public.brsr_assignment_blocks TO authenticated;

CREATE OR REPLACE FUNCTION public.can_access_block(
  target_org_id UUID,
  target_block_id TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.brsr_assignment_blocks b
    WHERE b.block_id = target_block_id
      AND public.can_access_question(target_org_id, b.question_code)
  );
$$;

COMMENT ON FUNCTION public.can_access_block(UUID, TEXT) IS
  'True when the caller may access the representative question_code for the block.';

-- Arguments are evaluated in the caller's scope, so an RLS policy cannot
-- accidentally compare brsr_assignment_blocks columns against themselves
-- (an unqualified `b.block_id = block_id` inside EXISTS resolves to b.block_id).
CREATE OR REPLACE FUNCTION public.block_triple_matches(
  target_block_id TEXT,
  target_panel_id TEXT,
  target_question_code TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.brsr_assignment_blocks b
    WHERE b.block_id = target_block_id
      AND b.panel_id = target_panel_id
      AND b.question_code = target_question_code
  );
$$;

COMMENT ON FUNCTION public.block_triple_matches(TEXT, TEXT, TEXT) IS
  'True when (block_id, panel_id, question_code) is a known row in brsr_assignment_blocks.';

GRANT EXECUTE ON FUNCTION public.block_triple_matches(TEXT, TEXT, TEXT) TO authenticated;

-- ── Tables ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.question_threads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  reporting_year TEXT NOT NULL,
  block_id TEXT NOT NULL REFERENCES public.brsr_assignment_blocks(block_id),
  panel_id TEXT NOT NULL,
  question_code TEXT NOT NULL,
  note_body TEXT,
  note_updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  note_updated_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, reporting_year, block_id)
);

CREATE INDEX IF NOT EXISTS idx_question_threads_org_year
  ON public.question_threads(org_id, reporting_year);

COMMENT ON COLUMN public.question_threads.question_code IS
  'Representative code for RLS via can_access_question; must match brsr_assignment_blocks.';

CREATE TABLE IF NOT EXISTS public.question_comments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  thread_id UUID NOT NULL REFERENCES public.question_threads(id) ON DELETE CASCADE,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  author_label TEXT NOT NULL DEFAULT 'Unknown',
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  edited_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_question_comments_thread
  ON public.question_comments(thread_id);

CREATE INDEX IF NOT EXISTS idx_question_comments_thread_created
  ON public.question_comments(thread_id, created_at);

COMMENT ON COLUMN public.question_comments.author_label IS
  'Snapshot of display_name/email at insert time; survives auth.users deletion.';

CREATE TABLE IF NOT EXISTS public.question_comment_reads (
  thread_id UUID NOT NULL REFERENCES public.question_threads(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (thread_id, user_id)
);

ALTER TABLE public.question_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_comment_reads ENABLE ROW LEVEL SECURITY;

-- ── Triggers: identity freeze + admin-only resolve ───────────────────────────

CREATE OR REPLACE FUNCTION public.question_threads_guard_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS DISTINCT FROM OLD.org_id
     OR NEW.reporting_year IS DISTINCT FROM OLD.reporting_year
     OR NEW.block_id IS DISTINCT FROM OLD.block_id
     OR NEW.panel_id IS DISTINCT FROM OLD.panel_id
     OR NEW.question_code IS DISTINCT FROM OLD.question_code THEN
    RAISE EXCEPTION 'question_threads identity columns are immutable'
      USING ERRCODE = '42501';
  END IF;

  IF (NEW.resolved_at IS DISTINCT FROM OLD.resolved_at
      OR NEW.resolved_by IS DISTINCT FROM OLD.resolved_by)
     AND public.current_user_role_slug() NOT IN ('admin', 'master') THEN
    RAISE EXCEPTION 'only admin/master may resolve or reopen threads'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_question_threads_guard_update ON public.question_threads;
CREATE TRIGGER trg_question_threads_guard_update
  BEFORE UPDATE ON public.question_threads
  FOR EACH ROW
  EXECUTE PROCEDURE public.question_threads_guard_update();

-- Author may edit body / soft-delete; admin/master may only soft-delete (not rewrite body).
CREATE OR REPLACE FUNCTION public.question_comments_guard_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.thread_id IS DISTINCT FROM OLD.thread_id
     OR NEW.org_id IS DISTINCT FROM OLD.org_id
     OR NEW.author_id IS DISTINCT FROM OLD.author_id
     OR NEW.author_label IS DISTINCT FROM OLD.author_label
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'question_comments identity columns are immutable'
      USING ERRCODE = '42501';
  END IF;

  IF NEW.body IS DISTINCT FROM OLD.body
     OR NEW.edited_at IS DISTINCT FROM OLD.edited_at THEN
    IF OLD.author_id IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'only the author may edit comment body'
        USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_question_comments_guard_update ON public.question_comments;
CREATE TRIGGER trg_question_comments_guard_update
  BEFORE UPDATE ON public.question_comments
  FOR EACH ROW
  EXECUTE PROCEDURE public.question_comments_guard_update();

-- Snapshot author_label from profiles at insert (server-side; ignore client value).
CREATE OR REPLACE FUNCTION public.question_comments_set_author_label()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  label TEXT;
BEGIN
  IF NEW.author_id IS NULL THEN
    NEW.author_label := COALESCE(NULLIF(trim(NEW.author_label), ''), 'Unknown');
    RETURN NEW;
  END IF;

  SELECT COALESCE(
    NULLIF(trim(p.display_name), ''),
    NULLIF(trim(p.email), ''),
    NEW.author_id::text
  )
  INTO label
  FROM public.profiles p
  WHERE p.id = NEW.author_id;

  NEW.author_label := COALESCE(label, NEW.author_id::text, 'Unknown');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_question_comments_set_author_label ON public.question_comments;
CREATE TRIGGER trg_question_comments_set_author_label
  BEFORE INSERT ON public.question_comments
  FOR EACH ROW
  EXECUTE PROCEDURE public.question_comments_set_author_label();

-- ── RLS: question_threads ────────────────────────────────────────────────────

DROP POLICY IF EXISTS "question_threads_select" ON public.question_threads;
DROP POLICY IF EXISTS "question_threads_insert" ON public.question_threads;
DROP POLICY IF EXISTS "question_threads_update" ON public.question_threads;

CREATE POLICY "question_threads_select"
  ON public.question_threads
  FOR SELECT
  USING (public.can_access_question(org_id, question_code));

CREATE POLICY "question_threads_insert"
  ON public.question_threads
  FOR INSERT
  WITH CHECK (
    public.can_access_question(org_id, question_code)
    AND public.block_triple_matches(block_id, panel_id, question_code)
  );

CREATE POLICY "question_threads_update"
  ON public.question_threads
  FOR UPDATE
  USING (public.can_access_question(org_id, question_code))
  WITH CHECK (
    public.can_access_question(org_id, question_code)
    AND public.block_triple_matches(block_id, panel_id, question_code)
  );

-- ── RLS: question_comments ───────────────────────────────────────────────────

DROP POLICY IF EXISTS "question_comments_select" ON public.question_comments;
DROP POLICY IF EXISTS "question_comments_insert" ON public.question_comments;
DROP POLICY IF EXISTS "question_comments_update" ON public.question_comments;

CREATE POLICY "question_comments_select"
  ON public.question_comments
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  );

CREATE POLICY "question_comments_insert"
  ON public.question_comments
  FOR INSERT
  WITH CHECK (
    author_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND t.org_id = org_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  );

CREATE POLICY "question_comments_update"
  ON public.question_comments
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
    AND (
      author_id = auth.uid()
      OR public.current_user_role_slug() IN ('admin', 'master')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
    AND (
      author_id = auth.uid()
      OR public.current_user_role_slug() IN ('admin', 'master')
    )
  );

-- ── RLS: question_comment_reads ──────────────────────────────────────────────

DROP POLICY IF EXISTS "question_comment_reads_select" ON public.question_comment_reads;
DROP POLICY IF EXISTS "question_comment_reads_insert" ON public.question_comment_reads;
DROP POLICY IF EXISTS "question_comment_reads_update" ON public.question_comment_reads;

CREATE POLICY "question_comment_reads_select"
  ON public.question_comment_reads
  FOR SELECT
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  );

CREATE POLICY "question_comment_reads_insert"
  ON public.question_comment_reads
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  );

CREATE POLICY "question_comment_reads_update"
  ON public.question_comment_reads
  FOR UPDATE
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.question_threads t
      WHERE t.id = thread_id
        AND public.can_access_question(t.org_id, t.question_code)
    )
  );
